### ISSUE TITLE
Proposal to take over the CodePlex project official in this community maintained repo

### ISSUE THREAD

**Issue by lextm** [phpmanager/phpmanager#1]
The CodePlex repo haven't been updated for years, and its installers do not work for IIS 10. There can be other issues with the code base, as PHP evolves fast recently.

There are existing repos on GitHub,

* https://github.com/edgardo001/PHPManagerForIIS-Versiones which hosts a few installers. But the original source of the installer files are not explicit enough.
* https://github.com/RonaldCarter/PHPManager An attempt to fork the repo, and is IIS 10 only.
* https://github.com/xoofx/PHPManager An attempt to switch to WiX based installers.

A few critical things are not covered by all above,

1. A full takeover of the previous project requires coverage of all supported IIS releases today (IIS 7.0 to 10.0).
1. The output installers must be made available in a trustable way, ideally digital signed.
1. Revive the documentation, like how to compile the code base from scratch.
1. Build a small group of developers to maintain the code base and fix trivial bugs.

To get started, I created the `phpmanager` organization on GitHub, and started this repo. Hope all future efforts can be merged here to revive this project.

All comments are welcome. 

> 2.0 Beta 2 release is at https://github.com/phpmanager/phpmanager/releases/tag/v2.0-beta2

**Comment by RonaldCarter** [comment]
I am happy to support this initiative, I would love to get some proper programmers on this as all I have done is from google searches
