### ISSUE TITLE
left-over files when upgrading from previous php manager version

### ISSUE THREAD

**Issue by mbiebl** [phpmanager/phpmanager#23]
In my case I upgraded from PHP manager 1.3.
After running the RC3 installer, the old installation directory  ```C:\Program Files (x86)\PHP Manager 1.3 for IIS 10```
was not cleaned up and contained a file named ```Web.Management.PHP.PowerShell.InstallState```

**Comment by lextm** [comment]
The scope of this issue would be changed to support only PHP Manager 1.0.x/1.1.x, and 1.2.x.

1.3/1.4/1.5 releases are not from this repo, so I have no control on them.

Right now the plan is to let 2.0 final release remove its own file during uninstallation.
