### ISSUE TITLE
upgrade routine broken

### ISSUE THREAD

**Issue by mbiebl** [phpmanager/phpmanager#28]
Hi,

I've just upgraded from v2.1 to v2.2. 
After the upgrade, PHPManager was no longer shown in IIS Manager.
I had to uninstall and then reinstall PHPManager. After that it was functional again and available in IIS Manager.

**Comment by jinhr** [comment]
I have exact same issue upgrading from v2.1 to v2.3. I have to run v2.3 installer again to see `PHP Manager` icon in IIS

**Comment by mbiebl** [comment]
I had a bit of a closer look:
After a fresh installation of 2.4:
```
PS C:\> Select-String PHP C:\Windows\System32\inetsrv\config\administration.config

Windows\System32\inetsrv\config\administration.config:113:        <add name="PHP"
type="Web.Management.PHP.PHPProvider, Web.Management.PHP, Version=2.4.0.0, Culture=neutral,
PublicKeyToken=41b215c155952069" />
Windows\System32\inetsrv\config\administration.config:169:            <add name="PHP" />
```
All good.
Now upgrade to 2.5:

```
PS C:\> Select-String PHP C:\Windows\System32\inetsrv\config\administration.config

Windows\System32\inetsrv\config\administration.config:113:        <add name="PHP"
type="Web.Management.PHP.PHPProvider, Web.Management.PHP, Version=2.4.0.0, Culture=neutral,
PublicKeyToken=41b215c155952069" />
Windows\System32\inetsrv\config\administration.config:169:            <add name="PHP" />
```
Not good, it still references the old version.
I tried to add some logging to the custom action, but this turned out to be next to impossible.
So I asked on the WiX users mailing list and they strongly recommened *not* to use InstallUtil but DTF.

http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2021-March/009670.html

So, I gave DTF a go. It not only it simplified the code significantly and made it possible to add proper logging, it also fixed the upgrade issue. I'll clean up the branch and submit it as PR.

**Comment by mbiebl** [comment]
@lextm See https://github.com/messageconcept/phpmanager/commit/0407b53f17ab65da4f07a54d6023f51fca303670
not quite done yet, but you get the picture where this is going.
Nice reduction in code + it fixes this issue.

**Comment by lextm** [comment]
@mbiebl We couldn't use DTF initially because it does not work well when .NET Framework 2.x was in the picture. See #9 for more background.

Luckily all those old platforms are now end of life (IIS 7 and 7.5), so I think it is time to move back to DTF. A pull request should be as easy as rolling back the relevant commits I made earlier, but you can definitely start from scratch.

**Comment by mbiebl** [comment]
>  A pull request should be as easy as rolling back the relevant commits I made earlier, but you can definitely start from scratch.

Which commits are those?

**Comment by mbiebl** [comment]
> A pull request should be as easy as rolling back the relevant commits I made earlier, but you can definitely start from scratch.

Fwiw, I'm not attached to having my changes merged as long as the upgrade issue is fixed. So if you prefer to roll back your own commits, that works for me too.

**Comment by lextm** [comment]
Instead of merging this pull request, I reverted the code back to its very beginning in #57 and achieved the same.

Now 2.11 has been downloaded about 1.6k and no more report on this issue occurred, so I think it is safe to close it now.

Thanks for your efforts.
