### ISSUE TITLE
When installing the x64 version on x64 OS, PowerShell snapin is not registered

### ISSUE THREAD

**Issue by pluraltouch** [phpmanager/phpmanager#29]
When installing the x64 version on x64 OS, PowerShell snapin is not registered, so Add-PsSnapin PHPManagerSnapin will not found it, because the DLL is not registered.

**Cause:**

Installutil probably did not run during the setup. It is not in the path, so I am not sure how should the installer find it. Anyway the plugin is not registere neither in the normal neither in the WOW64 hive.

**Workaround**

Important: Must run the 64 bit version of installutil. For this we must find the intallutil... for example:

`"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe" "C:\Program Files\PHP Manager 2 for IIS\Web.Management.PHP.PowerShell.dll"`

**Comment by robinmalik** [comment]
Struck by this on Windows Server 2016. Is there anything specific I can provide to help improve the fix?

**Comment by areis422** [comment]
I have this same issue. Can manually register all DLLs to both Framework and Framework64, but the installer should already be doing this.
