### ISSUE TITLE
New extension syntax isn't recognized properly

### ISSUE THREAD

**Issue by jinhr** [phpmanager/phpmanager#30]
According to comments documented in php.ini, there is new syntax for extension:
```
extension=<ext>
```
But this PHP manager v2.3.0.0 doesn't recognize the new syntax properly. It still only support deprecated syntax:
```
extension=php_<ext>.dll
```
Thus on the PHP Extensions pane, for example, **gd2** and **php_gd2.dll** are treated as two enabled extensions instead of one. And although **intl** is already enabled, there is still a **php_intl.dll** in the Disabled list.

I suggest PHP manager to support both new and old syntax. On the UI, it should deduplicate extension list and unify the format as `<ext>`.

Thanks!

![phpmanager-issue](https://user-images.githubusercontent.com/487410/53429384-8c2d7380-39ba-11e9-930a-9b610cceb22a.png)

**Comment by lextm** [comment]
It is not trivial to support both extension patterns (the current code base is not that flexible).

You'd better use the old "php_" syntax (even if PHP 7.2 and above support the new syntax).

Once PHP 7.1 reaches end of life this December, http://php.net/supported-versions.php we can easily switch to the new pattern.

**Comment by lextm** [comment]
Duplicate to #31.
