### ISSUE TITLE
Error: Add-PsSnapin PHPManagerSnapin

### ISSUE THREAD

**Issue by vjardin** [phpmanager/phpmanager#33]
It seems that the issue #29 is not fixed for some cases. Using:
   `Add-PsSnapin PHPManagerSnapin`
I have the same issues, it cannnot be added, see:

![image](https://user-images.githubusercontent.com/8383368/63379885-8c209600-c395-11e9-94e4-c5f203be5fe5.png)

**Comment by posixx** [comment]
Same here. How to solve?

**Comment by areis422** [comment]
I have this same issue. Can manually register all DLLs to both Framework and Framework64, but the installer should already be doing this.

**Comment by areis422** [comment]
Reference: #29

**Comment by mbiebl** [comment]
I have two possible fixes: one using the "new" module based mechanism and one using the WixPSExtension (old snap-in mechanism).
Would be grateful to have some feedback/testing

**Comment by robinmalik** [comment]
@lextm This used to work on W10 for me:

`."C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe" "C:\Program Files\PHP Manager 2 for IIS\Web.Management.PHP.PowerShell.dll"`

but on Windows 11, neither a standard install or using the above will make the module visible. I can't even find any evidence of it being created on the file system.
