### ISSUE TITLE
Upgrade to PHP7.4 give message that version is Obsulete

### ISSUE THREAD

**Issue by jansor** [phpmanager/phpmanager#34]
I am using the latest version installed via choco, at this momebt 2.3.0

When i add new PHP version to IIS, in this case PHP 7.4.0 then i get a warning message that the version is absolete. I can still add it and all works as expected. Only warning messge must be updated to include version 7.4 :)

Thanks for the Support
Greets

**Comment by lextm** [comment]
A new release is needed to address that, but it won't come too soon.

**Comment by umuench** [comment]
![23-12-_2019_13-35-01](https://user-images.githubusercontent.com/7505398/71358852-b6c06c80-258a-11ea-9065-39ac41e37b52.png)
![23-12-_2019_13-46-13](https://user-images.githubusercontent.com/7505398/71358854-b7590300-258a-11ea-96bf-0453083e1abb.png)

If it can help :)

**Comment by robinmalik** [comment]
Why is this closed if it's a valid bug?
