### ISSUE TITLE
How can I remove a PHP Version?

### ISSUE THREAD

**Issue by mhsimkin** [phpmanager/phpmanager#36]
How can I remove a PHP version from the PHP Manager?  I have an old version of PHP that didn't exist on disk.  In order to use the PHP Manager, I needed to recreate the path to that version, and copy the current version in.

Then I was able to register and change to the new version.  I would like to clean up my hard drive and remove the old version.  How can I remove that version from PHP Manager and IIS?

Thanks

-marc

**Comment by lextm** [comment]
That's a good question.

At this moment you have to reverse the steps in https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-a-php-website-on-iis/configuring-step-1-install-iis-and-php#13-download-and-install-php-manually

**Comment by mhsimkin** [comment]
Thanks.
