### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by tobiastromm** [phpmanager/phpmanager#41]
Hi.

Can you please update this file 

https://github.com/phpmanager/phpmanager/blob/d7c1f2aa0c09525d0ddf02c97b1cf05a76014f2c/Server/Config/PHPConfigHelper.cs

to reflect PHP 8 changes?

line 901 new PHPIniExtension("php_gd2.dll", true), must be changed to new PHPIniExtension("php_gd.dll", true),
line 907 new PHPIniExtension("php_xmlrpc.dll", true) must be removed.

https://bugs.php.net/bug.php?id=80416

Please, don't abandon this project, check https://www.reddit.com/r/PHP/comments/ho9dgq/microsoft_not_going_to_officially_support_php_8/fxgk1sc/ , Microsoft wouldn't be producing official builds, but someone will : - )

**Comment by lextm** [comment]
Thanks for the info.

The current code base does not handle such version specific issues very well, so some investigation is required. Examples include #30 .

Really hope that some guys from PHP community can take it over, as I personally no longer write any PHP.

**Comment by lextm** [comment]
Just shipped 2.5 release with PHP 8.0 version added in diagnostics. But not yet enough time to address issues like this.

Pull requests are welcome, so that such can be fixed in vNext.
