### ISSUE TITLE
Installed 2.6 RTW PHP Manager No longer shows in IIS

### ISSUE THREAD

**Issue by charlesstratton4** [phpmanager/phpmanager#47]
Hello,

I just installed PHP Manager 2.6 x64 bit version on windows server 2012 R2 and now php manager no longer shows in IIS? The php sites are still running but the manager plug-in is not showing.

**Comment by lextm** [comment]
Execute the MSI package with logging enabled (like demonstrated in https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec#examples-3), and then see what happens under the hood.

**Comment by 274188A** [comment]
I'm seeing the same - anyone know why this happens?

**Comment by vitsupport** [comment]
The same happened for version 2.7 RTW on Windows Server 2019 (not on 2016). Resolved by repairing install: "Apps & features" -> "Modify" (on PHP Manager 2 for IIS 2.7.0.0) -> "Repair"...
