### ISSUE TITLE
window2008 R2 can't install

### ISSUE THREAD

**Issue by nenge123** [phpmanager/phpmanager#52]
tips "requires .NET 4.5.2"

but i installed 4.7.2,
i remove 4.7.2, install 4.5.2 ,

tips "requires .NET 4.5.2" too

**Comment by lextm** [comment]
Windows Server 2008 R2 is no longer supported. You can refer to what platforms are still supported,

https://docs.phpmanager.xyz/getting-started/supported-platforms.html
