### ISSUE TITLE
php_opcache is a zend_extension

### ISSUE THREAD

**Issue by eduardomozart** [phpmanager/phpmanager#54]
Hello,
The PHP extension ``php_opcache.dll`` can be enabled through PHPManager, but it enables it with the ``extension`` directive, but it's a Zend extension and should be enabled through the ``zend_extension`` directive, otherwise, the following error is shown at PHP error log:

``
PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=php_opcache.dll from php.ini) in Unknown on line 0
``

**Comment by lextm** [comment]
While the fix is now in place, the actual release will wait till PHP 8.2 is out.

**Comment by lextm** [comment]
PHP 8.2 is now deferred to Dec 8. This patched PHP Manager release will also be delayed.
