### ISSUE TITLE
PHP Manager Icon invisible for version 2.9.0.0

### ISSUE THREAD

**Issue by jinhr** [phpmanager/phpmanager#56]
After I upgrade to v2.9.0.0, the PHP Manager icon is invisible in IIS.

If I uninstall v2.9.0.0 and install v2.8.0.0, the icon comes back in IIS

**Comment by lextm** [comment]
Expected. Not sure why right now, but a repair can bring it back.

**Comment by lextm** [comment]
You might check out 2.11 release, which changed how the IIS Manager registration is done.

**Comment by testworksau** [comment]
@lextm just letting you know that we upgraded from "PHP Manager 2 for IIS 2.5.0.0" to 2.12, which had the same outcome. 

Repairing also returned the icon to its rightful place.
