### ISSUE TITLE
Trojan :(

### ISSUE THREAD

**Issue by turric4n** [phpmanager/phpmanager#57]
Hi,

I tried to install latest artifact version of PHPManagerForIIS_x64 2.9 RTW (directly downloaded from here) and Windows Defender is blocking this. 

Temp\tmp80B9.tmp.iis.exe 
- Category (Trojan)
- Win32/Wacatac.H!ml

**Comment by joegasper** [comment]
[VirusTotal results](https://www.virustotal.com/gui/file/ec6dfdce31d20939963dc4fef33671ffef031407a182dda02d456c0bd66f903d/detection) on 2.10 RTW look good.

**Comment by turric4n** [comment]
MSI maybe... but `Temp\tmp80B9.tmp.iis.exe`

**Comment by lextm** [comment]
Fixed in 2.11 by restoring the classical registration approach. That no longer relies on the runtime-compiled executable, which is not signed and might be misunderstood by the virus detection algorithms.
