### ISSUE TITLE
PHP Setup showing incorrect information and crashes

### ISSUE THREAD

**Issue by rboy1** [phpmanager/phpmanager#59]
Running Windows Server 2019

PHP Setup shows that this PHP version is obsolete. The version installed is the latest 7.4.33 version. Don't know why it's saying that given that PHP Manager will not support v8

Also when one clicks on View PHP supported versions it crashes IIS Manager.

![image](https://user-images.githubusercontent.com/3846367/227643918-39952353-037e-48c5-a309-ca23dcbfd658.png)

**Comment by lextm** [comment]
7.x are all end of life now, so the message is correct.
