### ISSUE TITLE
PHP 8.3 Support needs to be added

### ISSUE THREAD

**Issue by jrose323** [phpmanager/phpmanager#60]
Need to add PHP v8.3 as a valid version.

**Comment by ethanwa** [comment]
I am also seeing this problem in IIS on Windows Server 2022 Standard

**Comment by Donkerg** [comment]
Hi,  Is there some way to fix the issue that gives the info warning :  This PHP release is already obsolete ?  PHP installed 8.3.3 ...

**Comment by lextm** [comment]
PHP on IIS/Windows is out of Microsoft support and fully relies on the community,

https://docs.phpmanager.xyz/getting-started/supported-platforms.html#php-on-windows-status

You should seriously consider migrating to PHP on Linux. We currently have no plan to produce a new release and address this issue.

**Comment by lextm** [comment]
Duplicated to #62
