### ISSUE TITLE
Registering a new PHP version to the website

### ISSUE THREAD

**Issue by s-mironov** [phpmanager/phpmanager#61]
Hi all.

Please advise, downloaded a clean php-8.2.6 and installed Web-Server and Web-CGI using PowerShell. After installing PHP Manager For IIS. (I'll tell you ahead and through modules manually installed the same result).

When I try to register a new PHP version with the command — New-PHPVersion -ScriptProcessor "$env:ProgramFiles\php8.2\php-cgi.exe" -SiteName "New Web Site" -VirtualPath "/"

 get an error:
New-PHPVersion : The process cannot access the file because another process has locked a portion of the file. (Exception from HRESULT: 0x80070021)
At line:1 char:1
+ New-PHPVersion -ScriptProcessor "$env:ProgramFiles\php8.2\php-cgi.exe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : NotSpecified: (::) [New-PHPVersion], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Web.Management.PHP.Powershell.NewPHPVersionCmdlet

Can you please tell me what I am doing wrong?  I've tried other PHP versions and manual downloads etc. I still get this error and have tried other versions of Windows Server, etc. Nothing helps ;(

I also understand the error and I have checked php-cgi.exe itself through all sorts of software and PowerShell commands and have not seen any problems in it.

**Comment by lextm** [comment]
Duplicate to #62
